#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Simple
version:      1.6
version_from: Simple.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
