---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6501, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Email::Date::Format: 0
  Test::More: 0.47
resources:
  x_Repository: http://github.com/rjbs/email-simple
version: 2.200_01
